name: lint-test-package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: cargo fetch

      - name: Check code formatting
        run: cargo fmt -- --check

      - name: Run lints
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test
